// ── status.js — QR Status Page ──
// Reads ?queue=Q023 from the URL

const params = new URLSearchParams(window.location.search);
let currentData = {};
let almostNotified = false;
let almostPollInterval = null;

const queueNum = params.get('queue');

// ── On page load ──
if (queueNum) {
  loadQueueStatus(queueNum);
} else {
  showError('No queue number found. Please scan your QR code again.');
}

// ============================================================
// LOAD QUEUE STATUS
// ============================================================
async function loadQueueStatus(queue) {
  try {
    const res = await fetch(`/api/queue/status?queue=${encodeURIComponent(queue)}`);

    if (!res.ok) {
      showError('Queue number not found. Please scan your QR code again.');
      return;
    }

    const data = await res.json();
    currentData = data;
    renderStatus(data);

    document.getElementById('page-loader').hidden = true;
    document.getElementById('main-content').hidden = false;

    startAlmostTurnPolling();

  } catch (err) {
    console.error('Failed to load queue status:', err);
    document.getElementById('page-loader').hidden = true;
    showError('Could not load your queue status. Please try again.');
  }
}

// ============================================================
// RENDER STATUS
// ============================================================
function renderStatus(data) {
  const isServing = data.status === 'Serving';
  const isCompleted = data.status === 'Completed';

  // ── Your queue number card ──
  const queueHeading = document.getElementById('your-queue-heading');
  if (queueHeading) queueHeading.textContent = data.queue_number;

  // Status badge
  const statusBadgeEl = queueHeading?.nextElementSibling;
  if (statusBadgeEl) {
    statusBadgeEl.textContent = isServing ? 'Now Serving' : isCompleted ? 'Completed' : 'Waiting';
    statusBadgeEl.className = isServing
      ? 'mb-1.5 text-xs font-medium px-2 py-0.5 rounded-[5px] bg-teal-50 text-teal-700'
      : isCompleted
        ? 'mb-1.5 text-xs font-medium px-2 py-0.5 rounded-[5px] bg-green-50 text-green-700'
        : 'mb-1.5 text-xs font-medium px-2 py-0.5 rounded-[5px] bg-gray-100 text-gray-500';
  }

  // Patient name greeting
  const greetingEl = document.getElementById('patient-greeting');
  if (greetingEl) {
    greetingEl.textContent = `Hello, ${data.patient_name ? data.patient_name.split(' ')[0] : 'Patient'}.`;
  }

  // Department and counter
  const dds = document.querySelectorAll('#your-queue-card dd');
  if (dds[0]) dds[0].textContent = data.department || '—';
  if (dds[1]) dds[1].textContent = data.counter || '—';

  // ── Position & Wait card ──
  const position = data.position ?? 0;

  const positionEl = document.getElementById('position-value');
  if (positionEl) {
    positionEl.textContent = isCompleted
      ? '—'
      : isServing
        ? 'Now'
        : `${position}${ordinal(position)}`;
  }

  const waitEl = document.getElementById('wait-value');
  if (waitEl) {
    waitEl.textContent = isCompleted
      ? 'Done'
      : isServing
        ? '~Now'
        : (data.estimated_wait || '—');
  }

  // Progress bar
  const progressBar = document.querySelector('[role="progressbar"] div');
  const progressPct = isServing || isCompleted
    ? 100
    : Math.max(5, 100 - (position - 1) * 15);
  if (progressBar) progressBar.style.width = `${progressPct}%`;

  // Now Serving label
  const nowServingLabel = document.getElementById('now-serving-label');
  if (nowServingLabel) nowServingLabel.textContent = data.now_serving || '—';

  // ── Queue Around You ──
  renderNearbyList(data.nearby, data.queue_number);

  // ── Email notice ──
  const emailAddressEl = document.getElementById('email-masked-address');
  if (emailAddressEl && data.email) {
    const [user, domain] = data.email.split('@');
    const masked = user.slice(0, 2) + '***@' + domain;
    emailAddressEl.textContent = masked;
  }

  // ── QR Code — use the one saved by generate-queue-form.js ──
  renderQRCode();

  // ── Download button ──
  const downloadBtn = document.getElementById('download-queue-card-btn');
  if (downloadBtn) {
    const newBtn = downloadBtn.cloneNode(true);
    downloadBtn.parentNode.replaceChild(newBtn, downloadBtn);
    newBtn.addEventListener('click', downloadQueueCard);
  }
}

// ============================================================
// RENDER QR CODE — reads from sessionStorage, no generation
// ============================================================
function renderQRCode() {
  const qrContainer = document.querySelector('#qr-code-card .qr-wrapper');
  if (!qrContainer) return;

  qrContainer.innerHTML = '';

  const savedQR = sessionStorage.getItem('lastQRDataURL');

  if (savedQR) {
    // Use QR already generated by generate-queue-form.js
    const img = document.createElement('img');
    img.src = savedQR;
    img.width = 120;
    img.height = 120;
    img.alt = 'Queue QR Code';
    img.style.display = 'block';
    qrContainer.appendChild(img);
    console.log('[QR] Loaded from sessionStorage (generate-queue-form.js)');
  } else {
    // Fallback: show a placeholder if no QR was saved
    // This happens when the user navigates directly to the status page
    // without going through the generate form first
    console.warn('[QR] No QR found in sessionStorage. User may have navigated directly.');
    const placeholder = document.createElement('div');
    placeholder.style.cssText = `
      width: 120px;
      height: 120px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 11px;
      color: #9CA3AF;
      border: 1px dashed #E5E7EB;
      border-radius: 6px;
      text-align: center;
      padding: 8px;
      box-sizing: border-box;
    `;
    placeholder.textContent = 'QR not available. Please generate a new queue.';
    qrContainer.appendChild(placeholder);
  }
}

// ============================================================
// NEARBY QUEUE LIST
// ============================================================
function renderNearbyList(nearby, myQueue) {
  const list = document.querySelector('#queue-around-card ol');
  if (!list || !nearby) return;

  list.innerHTML = nearby.map((item) => {
    const isYou = item.queue_number === myQueue;
    const isCompleted = item.status === 'Completed';
    const isServing = item.status === 'Serving';

    let badge = '';
    if (isCompleted) {
      badge = `<span class="text-xs font-medium px-2 py-0.5 rounded-[5px] bg-green-50 text-green-700 border border-green-200">Completed</span>`;
    } else if (isServing) {
      badge = `<span class="text-xs font-medium px-2 py-0.5 rounded-[5px] bg-[#EFF5FF] text-[#0052CC] border border-blue-200">Now Serving</span>`;
    } else {
      badge = `<span class="text-xs font-medium px-2 py-0.5 rounded-[5px] bg-gray-50 text-gray-500 border border-gray-200">Waiting</span>`;
    }

    const youPill = isYou
      ? `<span class="text-[11px] px-1.5 py-0.5 rounded-[4px] font-medium bg-blue-200 text-[#0052CC] ml-2">You</span>`
      : '';

    return `
      <li class="flex items-center justify-between h-9 border-b border-gray-100 last:border-0
        ${isYou ? 'border-l-2 border-l-[#0066FF] bg-[#EFF5FF] pl-2.5' : ''}"
        ${isYou ? 'aria-current="true"' : ''}>
        <div class="flex items-center gap-2">
          <span class="font-mono text-sm text-gray-700">${item.queue_number}</span>
          ${youPill}
        </div>
        ${badge}
      </li>
    `;
  }).join('');
}

// ============================================================
// ALMOST YOUR TURN — poll every 30s, notify once
// ============================================================
async function checkAlmostTurn() {
  const now = new Date().toLocaleTimeString('en-PH', { hour12: false });

  if (almostNotified) {
    console.log(`[EmailChecker] ${now} — already notified, skipping.`);
    return;
  }
  if (!currentData.queue_number) {
    console.log(`[EmailChecker] ${now} — no queue number, skipping.`);
    return;
  }
  if (currentData.status !== 'Waiting') {
    console.log(`[EmailChecker] ${now} — status is "${currentData.status}", skipping.`);
    return;
  }

  console.log(`[EmailChecker] ${now} — checking position for ${currentData.queue_number}...`);

  try {
    const res = await fetch(`/api/queue/status?queue=${encodeURIComponent(currentData.queue_number)}`);
    if (!res.ok) {
      console.warn(`[EmailChecker] ${now} — API returned ${res.status}, skipping.`);
      return;
    }

    const data = await res.json();
    currentData = { ...currentData, ...data };
    renderStatus(currentData);

    const position = data.position ?? 0;
    console.log(`[EmailChecker] ${now} — position: ${position}, email sent: ${almostNotified}`);

    if (position > 0 && position <= 2) {
      almostNotified = true;

      socket.emit('notify:almost', {
        email:          currentData.email,
        patient_name:   currentData.patient_name,
        queue_number:   currentData.queue_number,
        department:     currentData.department,
        counter:        currentData.counter,
        patients_ahead: position - 1,
      });

      console.log(`[EmailChecker] ${now} — it's almost your turn! Email dispatched to ${currentData.email} (position: ${position}, patients ahead: ${position - 1}).`);

      stopAlmostTurnPolling();
      console.log(`[EmailChecker] ${now} — polling stopped.`);
    } else {
      console.log(`[EmailChecker] ${now} — not close enough yet (position: ${position}), will check again in 30s.`);
    }

  } catch (err) {
    console.error(`[EmailChecker] ${now} — fetch failed:`, err);
  }
}

function startAlmostTurnPolling() {
  if (currentData.status === 'Serving' || currentData.status === 'Completed') return;

  checkAlmostTurn();
  almostPollInterval = setInterval(checkAlmostTurn, 5_000);
}

function stopAlmostTurnPolling() {
  if (almostPollInterval) {
    clearInterval(almostPollInterval);
    almostPollInterval = null;
  }
}

// ============================================================
// DOWNLOAD QUEUE CARD (PDF)
// ============================================================
function downloadQueueCard() {
  if (typeof window.jspdf === 'undefined') {
    alert('PDF download is not available yet.');
    return;
  }

  const queueNumber = currentData.queue_number || '—';
  const patientName = currentData.patient_name || 'Patient';
  const department = currentData.department || '—';
  const counter = currentData.counter || '—';
  const position = currentData.position || 0;
  const estimatedWait = currentData.estimated_wait || '—';
  const email = currentData.email || '—';
  const [u, d] = email.includes('@') ? email.split('@') : ['—', ''];
  const maskedEmail = email !== '—' ? u.slice(0, 2) + '***@' + d : '—';

  const now = new Date();
  const generatedDate = now.toLocaleDateString('en-PH');
  const generatedAt = now.toLocaleTimeString('en-PH', { hour: '2-digit', minute: '2-digit' });

  const { jsPDF } = window.jspdf;
  const W = 105, H = 175;
  const doc = new jsPDF({ unit: 'mm', format: [W, H] });

  // Header
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('MedQueue', W / 2, 14, { align: 'center' });

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(130);
  doc.text('HOSPITAL QUEUEING SYSTEM', W / 2, 20, { align: 'center' });

  // Queue number
  doc.setFontSize(42);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 102, 255);
  doc.text(queueNumber, W / 2, 38, { align: 'center' });

  // Divider
  doc.setDrawColor(220);
  doc.line(10, 44, W - 10, 44);

  // Info rows
  const rows = [
    ['Name', patientName],
    ['Email', maskedEmail],
    ['Department', department],
    ['Counter', counter],
    ['Position', position > 0 ? `${position}${ordinal(position)} in line` : '—'],
    ['Est. Wait', estimatedWait],
    ['Date', generatedDate],
    ['Time', generatedAt],
  ];

  doc.setFontSize(9);
  let y = 52;
  rows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(130);
    doc.text(label, 14, y);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(20);
    doc.text(String(value), 52, y);
    y += 7.5;
  });

  // ── QR code — use the one saved by generate-queue-form.js ──
  const savedQR = sessionStorage.getItem('lastQRDataURL');
  if (savedQR) {
    try {
      const qrSize = 32;
      doc.addImage(savedQR, 'PNG', (W - qrSize) / 2, y + 6, qrSize, qrSize);
      y += qrSize + 10;
      console.log('[PDF] QR added from sessionStorage');
    } catch (e) {
      console.warn('[PDF] QR embed failed:', e);
      y += 6;
    }
  } else {
    console.warn('[PDF] No QR in sessionStorage');
    y += 6;
  }

  // Footer
  doc.setDrawColor(220);
  doc.line(10, y + 2, W - 10, y + 2);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text('Please stay nearby the waiting area and keep your phone on.', W / 2, y + 9, { align: 'center' });
  doc.text('You will be notified by email when it\'s your turn.', W / 2, y + 14, { align: 'center' });

  doc.save(`QueueCard-${queueNumber}.pdf`);
}

// ============================================================
// ORDINAL SUFFIX
// ============================================================
function ordinal(n) {
  if (!n || n === 0) return '';
  const s = ['th', 'st', 'nd', 'rd'];
  const v = n % 100;
  return s[(v - 20) % 10] || s[v] || s[0];
}

// ============================================================
// SOCKET.IO — live updates
// ============================================================
const socket = io();

socket.on('queue:update', (data) => {
  if (!currentData.queue_number || !data.queues) return;

  const updated = data.queues.find(q => q.queue_number === currentData.queue_number);
  if (!updated) return;

  updated.now_serving = data.now_serving ?? updated.now_serving;
  updated.estimated_wait = data.estimated_wait ?? updated.estimated_wait;

  currentData = { ...currentData, ...updated };
  renderStatus(currentData);

  if (currentData.status === 'Serving' || currentData.status === 'Completed') {
    almostNotified = true;
    stopAlmostTurnPolling();
  }
});

socket.on('queue:done', (data) => {
  if (data.queue_number !== currentData.queue_number) return;
  currentData = { ...currentData, status: 'Completed', position: 0 };
  renderStatus(currentData);
  almostNotified = true;
  stopAlmostTurnPolling();
});

// ============================================================
// ERROR SCREEN
// ============================================================
function showError(message) {
  document.getElementById('page-loader').hidden = true;
  const main = document.getElementById('main-content');
  if (!main) return;
  main.hidden = false;
  main.innerHTML = `
    <div style="text-align:center; padding: 3rem 1rem;">
      <p style="font-size:15px; color:#374151; font-weight:600; margin-bottom:.5rem;">Something went wrong</p>
      <p style="font-size:13px; color:#6B7280; margin-bottom:1.5rem;">${message}</p>
      <a href="/" style="font-size:13px; color:#0066FF;">← Back to Queue Generator</a>
    </div>
  `;
}