services:
  - type: web
    name: medqueue
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 4000
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: SEMAPHORE_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false